receivers:
    filelog:
      include: [ /output/file.log ]

exporters:
    otlphttp:
      endpoint: "http://splunk:4318"

processors:
    resource:
        attributes:
          - key: com.splunk.sourcetype
            value: "mysourcetype"
            action: insert
          - key: com.splunk.source
            value: "mysource"
            action: insert

service:
    pipelines:
      logs:
        receivers: [filelog]
        processors: [resource]
        exporters: [otlphttp]
