receivers:
    file_log:
      include: [ /output/file.log ]

exporters:
    otlp_http:
      endpoint: "http://splunk:4318"
      headers:
        authorization: "Splunk 00000000-0000-0000-0000-0000000000000"

processors:
    resource:
        attributes:
          - key: com.splunk.sourcetype
            value: "mysourcetype"
            action: insert
          - key: com.splunk.source
            value: "mysource"
            action: insert

service:
    pipelines:
      logs:
        receivers: [file_log]
        processors: [resource]
        exporters: [otlp_http]
